# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- Production
- Development

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if contains(variables['Build.SourceBranch'], 'development') }}:
   BASEREF: '/CamerasDev/'
   CONFIG: 'development'

  ${{ if contains(variables['Build.SourceBranch'], 'production') }}:   
   BASEREF: '/Cameras/'
   CONFIG: 'production'

jobs: 
  - job: development
    condition: eq(variables.CONFIG, 'development') 
    steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'
        - script: echo "sourcebranch is  $(Build.SourceBranch) "
        - script: echo "baseref is  $(BASEREF)"
        - script: echo "config is  $(CONFIG)"
        - script: |
            npm install -g @angular/cli@14.2.0
            npm install
            ng build --configuration=$(CONFIG) --base-href $(BASEREF) --aot
          displayName: 'npm install and build'
        - script: tree "/home/vsts/work/1/s/"


        - task: CopyFiles@2
          inputs:
                SourceFolder: '/home/vsts/work/1/s/dist/test-camera'
                Contents: '**'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'

  - job: production
    condition: eq(variables.CONFIG, 'production')

    steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'
          - script: echo "sourcebranch is  $(Build.SourceBranch) "
          - script: echo "baseref is  $(BASEREF)"
          - script: echo "config is  $(CONFIG)"
          - script: |
              npm install -g @angular/cli@14.2.0
              npm install
              ng build --configuration=$(CONFIG) --base-href $(BASEREF) --aot
            displayName: 'npm install and build'

          - task: CopyFiles@2
            inputs:
                SourceFolder: '/home/vsts/work/1/s/dist/test-camera'
                Contents: '**'
                TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
                PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'